[build]
  command = "npm install && npm run build"
  publish = ".next/static"
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[scheduled_functions]]
  path = "/api/cleanup"
  schedule = "@daily"
